packages:
  - docs
  - packages/jssdk
  - packages/jssdk-nuxt
  - playgrounds/nuxt
  - playgrounds/cli

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - puppeteer
  - sharp
